
CREATE TABLE `cafestable` (
  `id` int(11) NOT NULL,
  `title` varchar(120) NOT NULL,
  `description` varchar(1400) NOT NULL,
  `photo` varchar(150) NOT NULL,
  `link` varchar(1500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `cafestable`
--

INSERT INTO `cafestable` (`id`, `title`, `description`, `photo`, `link`) VALUES
(1, 'Under the Golden Rose', 'This restaurant provides you with nice food and a place to rest after a long walk around Jewish Museum Lviv. Search through the Jewish menu. Mouthwatering pate, duck and hummus are the tastiest dishes. At the Golden Rose boasts tasty strudels. It might be nice to try delicious ale, beer or wine. You will be offered good coffee or great tea.\r\n\r\nMusicians make live music in the evening. This place is recommended for the accommodating waitstaff. The nice service is something these restaurateurs care about. Also, visitors recommend this spot because of attractive prices. The modern decor and spectacular atmosphere let guests feel relaxed here. Google users awarded this restaurant 4.5.', '../images/homeph/cafe1.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png '),
(2, 'Kumpel Na Rynku', 'Besides Chapel of the Boim Family, visit Craft&Kumpel in the vicinity. According to the guests\' comments, Israeli and Ukrainian dishes here are tasty and the menu is well-organized.You can share nicely cooked fish, salads and burgers with your friends and spend a nice time here. Clients visit this restaurant to drink good craft beer or delicious wine.\r\n\r\nIt\'s easy to find Craft&Kumpel due to the convenient location. The friendly staff works hard, stays positive and makes this place wonderful. Spectacular service is something that people note in their reviews. Pay reasonable prices for eating at this place. You will definitely like the cool atmosphere and nice decor.', '../images/homeph/cafe2.png', '../template/cafe_2_images/photo1.png ../template/cafe_2_images/photo2.png ../template/cafe_2_images/photo3.png ../template/cafe_2_images/photo4.png ../template/cafe_2_images/photo5.png ../template/cafe_2_images/photo6.png ../template/cafe_2_images/photo7.png ../template/cafe_2_images/photo8.png ../template/cafe_2_images/photo9.png'),
(3, 'Marevo', 'Both Armenian street and Marevo are recommended for visiting. Offering perfectly cooked pizza, chicken salads and zeama is the hallmark of this restaurant. Good wine or delicious beer will make your meal even more delicious and you\'ll certainly come back. According to the guests\' opinions, waiters offer good lemonade.\r\n\r\nMarevo offers food delivery for the convenience of its customers. The energetic waitstaff at this place can demonstrate how much they appreciate their visitors. The enjoyable service is something these restaurateurs care about. You will appreciate the spectacular decor and charming atmosphere of this spot. As for the Google rating, this restaurant received 4.6.', '../images/homeph/cafe3.png', '../template/cafe_3_images/photo1.png ../template/cafe_3_images/photo2.png ../template/cafe_3_images/photo3.png ../template/cafe_3_images/photo4.png ../template/cafe_3_images/photo5.png ../template/cafe_3_images/photo6.png ../template/cafe_3_images/photo7.png ../template/cafe_3_images/photo8.png ../template/cafe_3_images/photo9.png'),
(4, 'Under the Golden Rose', 'This restaurant provides you with nice food and a place to rest after a long walk around Jewish Museum Lviv. Search through the Jewish menu. Mouthwatering pate, duck and hummus are the tastiest dishes. At the Golden Rose boasts tasty strudels. It might be nice to try delicious ale, beer or wine. You will be offered good coffee or great tea.\r\n\r\nMusicians make live music in the evening. This place is recommended for the accommodating waitstaff. The nice service is something these restaurateurs care about. Also, visitors recommend this spot because of attractive prices. The modern decor and spectacular atmosphere let guests feel relaxed here. Google users awarded this restaurant 4.5.', '../images/homeph/cafe1.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png'),
(5, 'Cafe number 5', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas libero. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Vivamus porttitor turpis ac leo. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin in tellus sit amet nibh dignissim sagittis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla pulvinar eleifend sem. Phasellus et lorem id felis nonummy placerat.  Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '../template/cafe_1_images/photo1.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png'),
(6, 'Cafe number 6', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas libero. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Vivamus porttitor turpis ac leo. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin in tellus sit amet nibh dignissim sagittis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla pulvinar eleifend sem. Phasellus et lorem id felis nonummy placerat.  Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '../template/cafe_1_images/photo2.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png'),
(7, 'Cafe number 7', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas libero. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Vivamus porttitor turpis ac leo. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin in tellus sit amet nibh dignissim sagittis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla pulvinar eleifend sem. Phasellus et lorem id felis nonummy placerat.  Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '../template/cafe_1_images/photo4.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png'),
(8, 'Cafe number 8', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas libero. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Vivamus porttitor turpis ac leo. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin in tellus sit amet nibh dignissim sagittis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla pulvinar eleifend sem. Phasellus et lorem id felis nonummy placerat.  Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '../template/cafe_1_images/photo5.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png'),
(9, 'Cafe number 9', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas libero. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Vivamus porttitor turpis ac leo. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin in tellus sit amet nibh dignissim sagittis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla pulvinar eleifend sem. Phasellus et lorem id felis nonummy placerat.  Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '../template/cafe_1_images/photo6.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png'),
(10, 'Cafe number 10', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas libero. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Vivamus porttitor turpis ac leo. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin in tellus sit amet nibh dignissim sagittis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla pulvinar eleifend sem. Phasellus et lorem id felis nonummy placerat.  Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '../template/cafe_1_images/photo7.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png'),
(11, 'Cafe number 11', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas libero. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Vivamus porttitor turpis ac leo. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin in tellus sit amet nibh dignissim sagittis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla pulvinar eleifend sem. Phasellus et lorem id felis nonummy placerat.  Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '../template/cafe_1_images/photo8.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png'),
(12, 'Cafe number 12', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas libero. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Vivamus porttitor turpis ac leo. In laoreet, magna id viverra tincidunt, sem odio bibendum justo, vel imperdiet sapien wisi sed libero. Proin in tellus sit amet nibh dignissim sagittis. Nullam feugiat, turpis at pulvinar vulputate, erat libero tristique tellus, nec bibendum odio risus sit amet ante. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nulla pulvinar eleifend sem. Phasellus et lorem id felis nonummy placerat.  Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '../template/cafe_1_images/photo9.png', '../template/cafe_1_images/photo1.png ../template/cafe_1_images/photo2.png ../template/cafe_1_images/photo3.png ../template/cafe_1_images/photo4.png ../template/cafe_1_images/photo5.png ../template/cafe_1_images/photo6.png ../template/cafe_1_images/photo7.png ../template/cafe_1_images/photo8.png ../template/cafe_1_images/photo9.png');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cafestable`
--
ALTER TABLE `cafestable`
  ADD PRIMARY KEY (`id`);

